### ISSUE TITLE
2주차 개인 주제 제안

### ISSUE THREAD

**Issue by seoHyun99** [seoHyun99/android-study-log#1]
2주차 개인 주제로, 
**Android Handler** 내부 구조에 대해서 공부하려고 합니다.

https://developer.android.com/reference/android/os/Handler.html
https://developer.android.com/reference/android/os/HandlerThread.html

개인적으로 공부하며 생긴 궁금증과 @Erica1217 님도
내부 구조 한 번와 위 링크의 해당 문서 한 번 훑어 읽고 
일요일 전까지 남겨주신 질문을 바탕으로 발표하려고 합니다.

@Erica1217 화요일까지 피드백 부탁드려요.

**Comment by Erica1217** [comment]
넵 알겠습니다!
