### ISSUE TITLE
3주차 주제 추가 발표 제안

### ISSUE THREAD

**Issue by seoHyun99** [seoHyun99/android-study-log#10]
3주차 지난 스터디 내용을 정리하던 중에, 
다 같이 알면 좋을 법한 내용이라, 추가적으로 설명할 시간을 가질 수 있는지 묻고싶습니다.

지난 발표때는 LiveData와 ViewModel의 간단한 사용 예제와 사용하는 이유를 설명드렸다면
이번에는 추가적으로 LiveData의 내부 구조에 대해서 이야기 하고 싶습니다.

짧게 한 15분 정도라도 이야기 나눌 수 있는 시간이 있으면 좋을 것 같습니다.
지난 3주차에 했던 기본적인 사용법들만 알고 와도 무리없게 준비하겠습니다.

@Erica1217  @ParkSohyeon17 의견 부탁드립니다.

**Comment by Erica1217** [comment]
좋습니다 👍

**Comment by ParkSohyeon17** [comment]
네 알겠습니다.
