### ISSUE TITLE
2주차 스터디 장소 예약

### ISSUE THREAD

**Issue by seoHyun99** [seoHyun99/android-study-log#4]
2주차 스터디 장소 예약 @Erica1217 님 차례입니다.

1주차에 가려고 했던 강남역 스터디블룸 어떤가요?
(https://spacecloud.kr/space/5671)
시간은 동일하게 일요일 1시 ~ 4시로 예약해주시면 될 것 같습니다.

다른 곳을 염두해두고 계시다면 답 부탁드려요.

**Comment by Erica1217** [comment]
@seoHyun99  스터디블룸은 예약이 다 찼네요.

슈퍼스타트 1500 (인) https://spacecloud.kr/reserve/3936/5968
모임플러스 1500 (인)  https://spacecloud.kr/space/785

이렇게 두 개가 인당 1500원으로 가격은 같고 1시~3시 사이에 예약이 가능한 곳입니다.
슈퍼스타트는 1주차때 모임을 가졌던 곳 입니다.
모임플러스는 강남역에서 좀 떨어져있지만 ,자동취소가 명시되어있지 않는 것을 보아 없을 수도 있겠습니다. 장소랑 주의사항 한번 더 보시고 답 부탁드립니다.

**Comment by seoHyun99** [comment]
개인적으로 슈퍼스타트는 지난 번에 갔을 때 
윗층에서 들리는 소음이 너무 시끄러워서 불편했습니다.

이번에는 모임플러스로 가보는 게 어떨까요?

**Comment by Erica1217** [comment]
좋습니다. 👍 
4월 1일 (일)  1:00~4:00 예약했습니다.
