### ISSUE TITLE
3주차 개인 주제 제안

### ISSUE THREAD

**Issue by seoHyun99** [seoHyun99/android-study-log#6]
3주차 발표 주제로는 
지난 구글IO에서 발표된 **AAC(Android Architecture Components)** 중
**ViewModel과 LiveData**에 대해 발표하려고 합니다.

https://developer.android.com/topic/libraries/architecture/viewmodel.html
https://developer.android.com/topic/libraries/architecture/livedata.html
읽어와주시면 되는 문서는 Android Developer에 있는 공식 문서 링크 두 개 입니다.

https://www.youtube.com/watch?v=FrteWKKVyzI
추가로 위 동영상은 작년 구글 IO때 AAC에 대한 발표 내용인데 21분 전까지 발표내용과 관련 있습니다. 
관심있으신 분은 따로 참고하셔도 좋을 것 같아 첨부합니다.

@Erica1217 님과 @ParkSohyeon17 님은 스터디 전 날까지 해당 내용을 읽고 
궁금하신 점이 생기면 질문을 남겨주시면 좋을 것 같습니다. 추가해서 준비해가겠습니다.

확인 부탁드립니다.
@Erica1217 @ParkSohyeon17

**Comment by Erica1217** [comment]
네 주제 확인했습니다. 👍

**Comment by ParkSohyeon17** [comment]
주제 확인했습니다.
